extern class Error

func foo() ~ Error {
	throw Error.new()
}