extern class Error

func foo() {
	throw Error.new()
}