extern class Error

func foo() ~ Error {
	throw new Error()
}