extern class Error

func foo() {
	throw new Error()
}