extern Error, foo

throw new Error() unless foo